GET http://localhost:5148/games/1

###

GET http://localhost:5148/games

###

POST http://localhost:5148/games
Content-Type: application/json

{
   "name": "Ромашка",
  "genreId": "2",
   "price": 99.3743327569697,
  "releaseDate": "2017-10-18"
}

###

PUT http://localhost:5148/games/7
Content-Type: application/json

{
   "name": "Total War Rome9",
  "genreId": "1",
   "price": 39.99,
  "releaseDate": "2029-10-18"
}

###

DELETE http://localhost:5148/games/10

###