GET http://localhost:5148/games/19

###

GET http://localhost:5148/games

###

POST http://localhost:5148/games
Content-Type: application/json

{
   "name": "I will nevwer die",
  "genreId": "2",
   "price": 99.3743327569697,
  "releaseDate": "2017-10-18"
}

###

PUT http://localhost:5148/games/4
Content-Type: application/json

{
   "name": "Game 1",
  "genre": "Strategy",
   "price": 33.3743327569697,
  "releaseDate": "2017-10-18"
}

###

DELETE http://localhost:5148/games/10

###